#!/bin/sh

if [ -w "/dev/kmsg" ]; then
    exec >/dev/kmsg 2>/dev/kmsg
fi

# Generate mount units for all exported virtiofs shares.
# This mounts all the filesystems at boot time in the location indicated by the
# mount tag, rather than mounting them with (explicit) static systemd units or
# runtime agent support for host-dependent paths.
# This is the virtiofs variant of mount-generator, using mount tag exports.
echo "mount-generator: starting"
set -ex

normal_dir="$1"
# allow passing EXPORTS_DIR as a pre-mounted path for unit tests
exportsdir="$EXPORTS_DIR"
echo "mount-generator: $1 $EXPORTS_DIR"

if [ -z "$exportsdir" ]; then
    exportsdir="/run/vmtest-exports"
    echo "mount-generator: creating $exportsdir"
    mkdir -p "$exportsdir"
    echo "mount-generator: mounting exports in $exportsdir"
    mount -t virtiofs exports "$exportsdir"
    echo "mount-generator: mounted exports in $exportsdir"
    trap 'umount $exportsdir && rm -rf $exportsdir' EXIT
fi

mkdir -p "$normal_dir/local-fs.target.requires"
# when running in metalos, local-fs.target will have already been activated in
# the initrd, so we need to make it a dependency of the workload (which is sshd
# to run the test)
mkdir -p "$normal_dir/workload-pre.target.requires"

for unit in "$exportsdir"/*.mount
do
    echo "mount-generator: processing $unit"
    cp "$unit" "$normal_dir"/
    unit="$(basename "$unit")"
    ln -s "$normal_dir/$unit" "$normal_dir/local-fs.target.requires/$unit"
    # In MetalOS vmtests, local-fs.target will be marked as completed in the
    # initrd, so add this mount unit to workload-pre.target.requires to ensure
    # it gets started before running the test (which is in workload.target)
    ln -s "$normal_dir/$unit" "$normal_dir/workload-pre.target.requires/$unit"
done
