load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "family",
    default = "none",
    values = [
        "none",
        "centos",
        "fedora",
        "rhel",
        "debian",
        "wolfi",
    ],
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "wolfi",
    constraint_setting = ":family",
    visibility = ["PUBLIC"],
)
