load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "family",
    default = "none",
    values = [
        "none",
        "centos",
        "fedora",
        "rhel",
    ],
    visibility = ["PUBLIC"],
)
