load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "family",
    default = "none",
    values = [
        "none",
        "centos",
        "fedora",
        "rhel",
    ],
    visibility = ["PUBLIC"],
)

# Backwards compatibility aliases - will be removed incrementally
fb_native.configuration_alias(
    name = "fedora",
    actual = ":family[fedora]",
    visibility = ["PUBLIC"],
)

fb_native.configuration_alias(
    name = "rhel",
    actual = ":family[rhel]",
    visibility = ["PUBLIC"],
)
