load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "virt-setting",
    default = "none",
    values = [
        "none",
        "virt-cd",
    ],
    visibility = ["PUBLIC"],
)
