load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "virt-setting",
    default = "none",
    values = [
        "none",
        "virt-cd",
    ],
    visibility = ["PUBLIC"],
)

# Backwards compatibility aliases - will be removed incrementally
fb_native.configuration_alias(
    name = "none",
    actual = ":virt-setting[none]",
    visibility = ["PUBLIC"],
)

fb_native.configuration_alias(
    name = "virt-cd",
    actual = ":virt-setting[virt-cd]",
    visibility = ["PUBLIC"],
)
