load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")

system_genrule_toolchain(name = "genrule", visibility = ["PUBLIC"])
system_python_bootstrap_toolchain(name = "python_bootstrap", visibility = ["PUBLIC"])
noop_test_toolchain(name = "test", visibility = ["PUBLIC"])
