load("@prelude//:rules.bzl", "platform")
load(":strip_configuration.bzl", "strip_configuration")

oncall("antlir")

platform(
    name = "empty-platform",
    # a totally empty platform
    visibility = ["PUBLIC"],
)

strip_configuration(
    name = "strip-configuration",
)

strip_configuration(
    name = "arch-only",
    keep_constraints = [
        "ovr_config//cpu/constraints:cpu",
    ],
)
