load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "systemd-setting",
    default = "unconfigured",
    values = [
        "unconfigured",
        "systemd-cd",
        "systemd-stable",
        "systemd-canary",
    ],
    visibility = ["PUBLIC"],
)
