load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@prelude//:rules.bzl", "constraint")

oncall("antlir")

constraint(
    name = "systemd-setting",
    default = "unconfigured",
    values = [
        "unconfigured",
        "systemd-cd",
        "systemd-stable",
        "systemd-canary",
    ],
    visibility = ["PUBLIC"],
)

# Backwards compatibility aliases - will be removed incrementally
fb_native.configuration_alias(
    name = "unconfigured",
    actual = ":systemd-setting[unconfigured]",
    visibility = ["PUBLIC"],
)

fb_native.configuration_alias(
    name = "systemd-cd",
    actual = ":systemd-setting[systemd-cd]",
    visibility = ["PUBLIC"],
)

fb_native.configuration_alias(
    name = "systemd-stable",
    actual = ":systemd-setting[systemd-stable]",
    visibility = ["PUBLIC"],
)

fb_native.configuration_alias(
    name = "systemd-canary",
    actual = ":systemd-setting[systemd-canary]",
    visibility = ["PUBLIC"],
)
